### ISSUE TITLE
Couldn't connect mysql in setting

### ISSUE THREAD

**Issue by zdnet** [icescrum/iceScrum-docker#2]
![1](https://cloud.githubusercontent.com/assets/1091809/25116718/12663af4-2441-11e7-832b-be85b587e533.png)

follow the docker setup guide but could not connect mysql, any suggestion?

**Comment by vbarrier** [comment]
does the host named "mysql" is resolved by the server?

**Comment by zdnet** [comment]
i setup by docker-compose, according to below config file, the host name should be "mysql", and it already running at docker

version: '2'
services:
  mysql:
    image: icescrum/mysql
    volumes:
      - ~/docker/icescrum/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  icescrum:
    image: icescrum/icescrum
    ports:
      - "10090:8080"
    volumes:
      - ~/docker/icescrum/icescrum:/root
    links:
      - mysql

**Comment by zdnet** [comment]
i also tried another way but still failed:

docker network create --driver bridge is_net
docker run --name mysql -v ~/docker/icescrum/mysql:/var/lib/mysql --net=is_net -e MYSQL_ROOT_PASSWORD=password -d icescrum/mysql
docker run --name icescrum -e ICESCRUM_HOST=10.222.225.56 -e ICESCRUM_PORT=10090 -e ICESCRUM_CONTEXT=/ -v ~/docker/icescrum/icescrum:/root --net=is_net -p 10090:8080 icescrum/icescrum

**Comment by noullet** [comment]
Hi,

First, a few more questions:

1. What OS/version are you running Docker on? 
2. Do you use Docker inside a VM or inside docker-machine?
3. Which version of Docker do you use? `$ docker version`

This is very likely to be a permission issue which prevents MySQL to write into `/var/lib/mysql` (which is actually `~/docker/icescrum/mysql` in your case).

Our MySQL image is derived from the official one and it adds a few workarounds to manage permission issues. Apparently they don't work in your context.

**Comment by zdnet** [comment]
Hi,
Running at Mac OS 10.12.4, inside docker-machine, docker version is 17.03.1-ce.
Actually i can run other mysql container with docker-compose and connect successfully. if it's caused by permission issue i will continue to fix it.
Thanks
